version: '3'
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - /opt/app/mysql/lib:/var/lib/mysql
      - /opt/app/mysql/mysqlBackup:/data/mysqlBackup
    ports:
      - "8002:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=qwer1234"
      - "TZ=Asia/Shanghai"