version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    privileged: true
    volumes:
      - /opt/app/mysql/mydir:/mydir
      - /opt/app/mysql/datadir:/var/lib/mysql
      - /opt/app/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /opt/app/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=qwer1234"
      - "TZ=Asia/Shanghai"
    ports:
      - 8002:3306